name = "faceoff"
type = "webpack"
account_id = "b66bd359758e73b1545c12556273fbc4"
workers_dev = false
route = "faceoffus.com/*"
zone_id = "e88dbd82f20de2247d656304a916f261"
webpack_config = "webpack.config.js"

[site]
bucket = "public"
entry-point = "workers-site"
